/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author marcosisaacarayaabarca
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param args
     */
    
    public static String fechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
    return formatoFecha.format(fecha);
    }
    
    public static void main(String args[]){
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            javax.swing.JFrame frame = new javax.swing.JFrame("Ventana Principal");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600); // tamaño de la ventana
            frame.add(new VentanaPrincipal());
            frame.setLocationRelativeTo(null); // centrar la ventana
            frame.setVisible(true);
        }
    });
     
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        appnombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Principal = new javax.swing.JButton();
        Principal1 = new javax.swing.JButton();
        Principal2 = new javax.swing.JButton();
        Principal3 = new javax.swing.JButton();
        Principal4 = new javax.swing.JButton();
        Principal5 = new javax.swing.JButton();
        Encabezado = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Desarrollo = new javax.swing.JPanel();
        Mensaje_Bienvenida = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Menu.setBackground(new java.awt.Color(0, 102, 255));
        Menu.setPreferredSize(new java.awt.Dimension(270, 640));

        appnombre.setFont(new java.awt.Font("Devanagari MT", 3, 14)); // NOI18N
        appnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appnombre.setText("POWERLAB");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.9F);
        jSeparator1.setAlignmentY(0.9F);

        Principal.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal.setForeground(new java.awt.Color(255, 255, 255));
        Principal.setText("Principal");
        Principal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal.setBorderPainted(false);
        Principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal.setIconTextGap(10);

        Principal1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal1.setForeground(new java.awt.Color(255, 255, 255));
        Principal1.setText("Principal");
        Principal1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal1.setBorderPainted(false);
        Principal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal1.setIconTextGap(10);

        Principal2.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal2.setForeground(new java.awt.Color(255, 255, 255));
        Principal2.setText("Principal");
        Principal2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal2.setBorderPainted(false);
        Principal2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal2.setIconTextGap(10);

        Principal3.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal3.setForeground(new java.awt.Color(255, 255, 255));
        Principal3.setText("Principal");
        Principal3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal3.setBorderPainted(false);
        Principal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal3.setIconTextGap(10);

        Principal4.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal4.setForeground(new java.awt.Color(255, 255, 255));
        Principal4.setText("Principal");
        Principal4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal4.setBorderPainted(false);
        Principal4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal4.setIconTextGap(10);

        Principal5.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal5.setForeground(new java.awt.Color(255, 255, 255));
        Principal5.setText("Principal");
        Principal5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal5.setBorderPainted(false);
        Principal5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal5.setIconTextGap(10);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addComponent(Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Principal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Principal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Principal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Principal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Principal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(appnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Encabezado.setBackground(new java.awt.Color(51, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(750, 150));

        mensaje1.setBackground(new java.awt.Color(51, 51, 51));
        mensaje1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        mensaje1.setForeground(new java.awt.Color(0, 0, 0));
        mensaje1.setText("Administracion Sistema");

        mensaje2.setFont(new java.awt.Font("Didot", 2, 18)); // NOI18N
        mensaje2.setForeground(new java.awt.Color(0, 0, 0));
        mensaje2.setText("Fecha:  ");

        Fecha.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        Fecha.setText("jLabel1");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addComponent(mensaje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        Desarrollo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesarrolloLayout = new javax.swing.GroupLayout(Desarrollo);
        Desarrollo.setLayout(DesarrolloLayout);
        DesarrolloLayout.setHorizontalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesarrolloLayout.setVerticalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Mensaje_Bienvenida.setFont(new java.awt.Font("Devanagari MT", 1, 18)); // NOI18N
        Mensaje_Bienvenida.setText("BIENVENIDOS A POWERLAB");
        Mensaje_Bienvenida.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Desarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mensaje_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Mensaje_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Desarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        Mensaje_Bienvenida.getAccessibleContext().setAccessibleName("Bienvenida");
    }// </editor-fold>//GEN-END:initComponents
    
    //configuracion estilos letras
    private void initStyles(){
        Mensaje_Bienvenida.putClientProperty("FlatLaf.style", "font: 200% $light.font");
        Mensaje_Bienvenida.setForeground(Color.DARK_GRAY);
        mensaje1.putClientProperty( "FlatLaf.style", "font: bold $h00.regular.font" );
        mensaje1.setForeground(Color.RED);
        mensaje2.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        mensaje2.setForeground(Color.white);
        Fecha.putClientProperty("FlatLaf.style", "font: bold 24 $light.font");
        Fecha.setForeground(Color.white);
        appnombre.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        appnombre.setForeground(Color.white);
        //Mostrar fecha
        Fecha.setText(fechaActual());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desarrollo;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Mensaje_Bienvenida;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Principal;
    private javax.swing.JButton Principal1;
    private javax.swing.JButton Principal2;
    private javax.swing.JButton Principal3;
    private javax.swing.JButton Principal4;
    private javax.swing.JButton Principal5;
    private javax.swing.JLabel appnombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    // End of variables declaration//GEN-END:variables

}

