/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;


/**
 *
 * @author marcosisaacarayaabarca
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        initStyles();
        SetDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param args
     */
    public void SetDate(){
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Junio", "Julio", "Agosto",
        "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    Fecha.setText("Hoy es: " + dia+ " de " + meses[month - 1]+ " de "+ year);
    }
    
    public static void main(String args[]){
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            javax.swing.JFrame frame = new javax.swing.JFrame("Ventana Principal");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600); // tamaño de la ventana
            frame.add(new VentanaPrincipal());
            frame.setLocationRelativeTo(null); // centrar la ventana
            frame.setVisible(true);
        }
    });
     
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        appnombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Principal = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Registro = new javax.swing.JButton();
        Medicion = new javax.swing.JButton();
        Ejercicio = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        Encabezado = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Desarrollo = new javax.swing.JPanel();
        Mensaje_Bienvenida = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(0, 102, 255));
        Menu.setPreferredSize(new java.awt.Dimension(270, 640));

        appnombre.setFont(new java.awt.Font("Devanagari MT", 3, 24)); // NOI18N
        appnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appnombre.setText("POWERLAB");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.9F);
        jSeparator1.setAlignmentY(0.9F);

        Principal.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal.setForeground(new java.awt.Color(255, 255, 255));
        Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home-outline.png"))); // NOI18N
        Principal.setText("Principal");
        Principal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal.setBorderPainted(false);
        Principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal.setIconTextGap(10);

        Usuario.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user_icon_150670.png"))); // NOI18N
        Usuario.setText("Usuario");
        Usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Usuario.setBorderPainted(false);
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Usuario.setIconTextGap(10);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Registro.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setIcon(new javax.swing.ImageIcon("/Users/marcosisaacarayaabarca/Documents/thefreeforty_register_icon-icons.com_66338.png")); // NOI18N
        Registro.setText("Registro");
        Registro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Registro.setBorderPainted(false);
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Registro.setIconTextGap(10);
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        Medicion.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Medicion.setForeground(new java.awt.Color(255, 255, 255));
        Medicion.setIcon(new javax.swing.ImageIcon("/Users/marcosisaacarayaabarca/Documents/waist_measurement_icon_224826.png")); // NOI18N
        Medicion.setText("Medicion");
        Medicion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Medicion.setBorderPainted(false);
        Medicion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Medicion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Medicion.setIconTextGap(10);

        Ejercicio.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Ejercicio.setForeground(new java.awt.Color(255, 255, 255));
        Ejercicio.setIcon(new javax.swing.ImageIcon("/Users/marcosisaacarayaabarca/Documents/exercise_dumbbells_gym_fitness_diet_icon_149053.png")); // NOI18N
        Ejercicio.setText("Ejercicio");
        Ejercicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Ejercicio.setBorderPainted(false);
        Ejercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ejercicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ejercicio.setIconTextGap(10);
        Ejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjercicioActionPerformed(evt);
            }
        });

        Salida.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Salida.setForeground(new java.awt.Color(255, 255, 255));
        Salida.setIcon(new javax.swing.ImageIcon("/Users/marcosisaacarayaabarca/Documents/log-out_icon-icons.com_50106.png")); // NOI18N
        Salida.setText("Salir");
        Salida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Salida.setBorderPainted(false);
        Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Salida.setIconTextGap(10);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(appnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Medicion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(appnombre)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Medicion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Encabezado.setBackground(new java.awt.Color(51, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(750, 150));

        mensaje1.setBackground(new java.awt.Color(51, 51, 51));
        mensaje1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        mensaje1.setForeground(new java.awt.Color(0, 0, 0));
        mensaje1.setText("Sistema del Gimnasio");

        mensaje2.setFont(new java.awt.Font("Didot", 2, 18)); // NOI18N
        mensaje2.setForeground(new java.awt.Color(0, 0, 0));
        mensaje2.setText("Fecha:  ");

        Fecha.setFont(new java.awt.Font("Gujarati MT", 2, 24)); // NOI18N
        Fecha.setText("jLabel1");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addComponent(mensaje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Desarrollo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesarrolloLayout = new javax.swing.GroupLayout(Desarrollo);
        Desarrollo.setLayout(DesarrolloLayout);
        DesarrolloLayout.setHorizontalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesarrolloLayout.setVerticalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Mensaje_Bienvenida.setFont(new java.awt.Font("Devanagari MT", 1, 18)); // NOI18N
        Mensaje_Bienvenida.setText("BIENVENIDOS A POWERLAB");
        Mensaje_Bienvenida.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Desarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mensaje_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Mensaje_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Desarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        Mensaje_Bienvenida.getAccessibleContext().setAccessibleName("Bienvenida");
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void EjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EjercicioActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroActionPerformed
    
    //configuracion estilos letras
    private void initStyles(){
        Mensaje_Bienvenida.putClientProperty("FlatLaf.style", "font: 200% $light.font");
        Mensaje_Bienvenida.setForeground(Color.DARK_GRAY);
        mensaje1.putClientProperty( "FlatLaf.style", "font: bold $h00.regular.font" );
        mensaje1.setForeground(Color.white);
        mensaje2.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        mensaje2.setForeground(Color.white);
        Fecha.putClientProperty("FlatLaf.style", "font: bold 24 $light.font");
        Fecha.setForeground(Color.white);
        appnombre.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        appnombre.setForeground(Color.white);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desarrollo;
    private javax.swing.JButton Ejercicio;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton Medicion;
    private javax.swing.JLabel Mensaje_Bienvenida;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Principal;
    private javax.swing.JButton Registro;
    private javax.swing.JButton Salida;
    private javax.swing.JButton Usuario;
    private javax.swing.JLabel appnombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    // End of variables declaration//GEN-END:variables

}

